#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing up connections to /dev/*"
echo ""

sudo cp "$(rospack find idmind_config)"/config/udev_rules/*.rules /etc/udev/rules.d

echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
#sudo udevadm trigger --action=change